openapi: '3.0.0'
info:
  version: 1.0.0
  title: Json Viewer AI API
  license:
    name: MIT
servers:
  - url: http://api.jsonviewer.ai/v1
paths:
  /json/validate:
    get:
      summary: List validations
      operationId: listValidations
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of validations
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Validations'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Run validation
      operationId: runValidation
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /json/validate/{validationId}:
    get:
      summary: Get validation
      operationId: getValidation
      parameters:
        - name: validationId
          in: path
          required: true
          description: The id of the validation result to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Validations'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /json/beautify:
    get:
      summary: List beautifications
      operationId: listBeautifications
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of beautifications
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Beautifications'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Validation:
      required:
        - id
        - status
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string
        message:
          type: string
    Validations:
      type: array
      items:
        $ref: '#/components/schemas/Validation'
    Beautification:
      required:
        - id
        - result
      properties:
        id:
          type: integer
          format: int64
        result:
          type: string
    Beautifications:
      type: array
      items:
        $ref: '#/components/schemas/Beautification'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string